name: ReVanced

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hntgl/YT-Re
          token: ${{ secrets.GH_PAT }} 
          path: scripts
      
      - name: Setup JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Download and Build APK
        run: ./scripts/build.sh -r
              
      - name: Set current date as env variable
        run: echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV && echo "date_now_nodashes=$(date +'%Y%m%d')" >> $GITHUB_ENV
        
      - uses: r0adkll/sign-android-release@v1
        name: Sign APK
        with:
          releaseDirectory: build
          signingKeyBase64: '${{ secrets.SIGNING_KEY }}'
          alias: '${{ secrets.ALIAS }}'
          keyStorePassword: '${{ secrets.KEY_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.KEY_PASSWORD }}'
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
          
      - name: Generate SHA256 checksums for the signed APK file
        run: ./scripts/sha256gen.sh -r
      
      - uses: marvinpinto/action-automatic-releases@latest
        name: Release ReVanced
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.date_now_nodashes }}-yt"
          title: "ReVanced ${{ env.date_now }}"
          prerelease: false
          files: |
            build/*signed.apk
            build/*.txt
            microg.apk
